In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('nba.csv')
df2 = pd.read_csv('iris.csv')

In [3]:
df1.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [4]:
grp = df1.groupby("Team")['Salary']
lst = grp.apply(list)
print(lst)

Team
Atlanta Hawks             [2000000.0, 1304520.0, 2854940.0, 12000000.0, ...
Boston Celtics            [7730337.0, 6796117.0, nan, 1148640.0, 5000000...
Brooklyn Nets             [3425510.0, 845059.0, 1500000.0, 1335480.0, 63...
Charlotte Hornets         [13125306.0, 947276.0, 189455.0, 947276.0, 525...
Chicago Bulls             [845059.0, 2250000.0, 16407500.0, 4500000.0, 5...
Cleveland Cavaliers       [1147276.0, 8193029.0, 16407501.0, 22970500.0,...
Dallas Mavericks          [1449000.0, 4290000.0, 1100602.0, 3950313.0, 4...
Denver Nuggets            [2814000.0, 3000000.0, 3533333.0, 10449438.0, ...
Detroit Pistons           [2500000.0, 6500000.0, 2170465.0, 111444.0, 12...
Golden State Warriors     [2500000.0, 3873398.0, 13800000.0, 947276.0, 1...
Houston Rockets           [8193030.0, 306527.0, 6486486.0, 8229375.0, 12...
Indiana Pacers            [4050000.0, 1007026.0, 10300000.0, 17120106.0,...
Los Angeles Clippers      [1100602.0, 111444.0, 5675000.0, 525093.0, 965...
Los Angeles Lakers        [3000000.0, 845059.0, 700000.0, 25000000.0, 84...
Memphis Grizzlies         [1404600.0, 5158539.0, 5000000.0, 3542500.0, 4...
Miami Heat                [22192730.0, 10151612.0, 14783000.0, 947276.0,...
Milwaukee Bucks           [1953960.0, 3000000.0, 2399040.0, 947276.0, 16...
Minnesota Timberwolves    [3950001.0, 1474440.0, 8500000.0, 1282080.0, 2...
New Orleans Pelicans      [4389607.0, 8500000.0, 9213483.0, 1100602.0, 3...
New York Knicks           [8000000.0, 1635476.0, 30888.0, 22875000.0, 74...
Oklahoma City Thunder     [2279040.0, 3750000.0, 20158622.0, 3135000.0, ...
Orlando Magic             [947276.0, 2288205.0, 4171680.0, 3741480.0, 79...
Philadelphia 76ers        [nan, 947276.0, 1000000.0, 4626960.0, 845059.0...
Phoenix Suns              [13500000.0, 2127840.0, 206192.0, 13000000.0, ...
Portland Trail Blazers    [525093.0, 8042895.0, 625093.0, 947276.0, 6980...
Sacramento Kings          [981348.0, 1015421.0, 6060606.0, 1449187.0, 28...
San Antonio Spurs         [19689000.0, 1142880.0, 947276.0, 7500000.0, 5...
Toronto Raptors           [2814000.0, 1524000.0, 13600000.0, 10050000.0,...
Utah Jazz                 [4775000.0, 2658240.0, 9463484.0, 3777720.0, 1...
Washington Wizards        [4000000.0, 5694674.0, 4375000.0, 561716.0, 33...
Name: Salary, dtype: object

In [5]:
summary = grp.agg(['mean','median','min','max','std'])
summary

,mean,median,min,max,std
Team,,,,,
Atlanta Hawks,4.860197e+06,2854940.0,525093.0,18671659.0,5.194508e+06
Boston Celtics,4.181505e+06,3021242.5,1148640.0,12000000.0,3.146033e+06
Brooklyn Nets,3.501898e+06,1335480.0,134215.0,19689000.0,5.317817e+06
Charlotte Hornets,5.222728e+06,4204200.0,189455.0,13500000.0,4.538601e+06
Chicago Bulls,5.785559e+06,2380440.0,525093.0,20093064.0,6.251088e+06
Cleveland Cavaliers,7.642049e+06,4975000.0,111196.0,22970500.0,7.730329e+06
Dallas Mavericks,4.746582e+06,3950313.0,525093.0,16407500.0,5.030279e+06
Denver Nuggets,4.294424e+06,2907000.0,258489.0,14000000.0,4.320214e+06
Detroit Pistons,4.477884e+06,2891760.0,111444.0,16000000.0,4.668478e+06
Golden State Warriors,5.924600e+06,3815000.0,289755.0,15501000.0,5.664282e+06
Houston Rockets,5.018868e+06,2288205.0,200600.0,22359364.0,6.414749e+06
Indiana Pacers,4.450122e+06,4000000.0,211744.0,17120106.0,4.584514e+06
Los Angeles Clippers,6.323643e+06,3110796.0,111444.0,21468695.0,7.600225e+06
Los Angeles Lakers,4.784695e+06,1724250.0,525093.0,25000000.0,6.835688e+06
Memphis Grizzlies,5.467920e+06,4544009.5,700902.0,19688000.0,5.201676e+06
Miami Heat,6.347359e+06,2481720.0,261894.0,22192730.0,7.848628e+06
Milwaukee Bucks,4.350220e+06,2254167.0,295327.0,16407500.0,4.875071e+06
Minnesota Timberwolves,4.593054e+06,2148360.0,947276.0,12700000.0,4.139625e+06
New Orleans Pelicans,4.355304e+06,2850000.0,55722.0,15514031.0,4.537874e+06
New York Knicks,4.581494e+06,2225421.0,30888.0,22875000.0,5.952487e+06
Oklahoma City Thunder,6.251020e+06,3344000.0,222888.0,20158622.0,6.632400e+06
Orlando Magic,4.297248e+06,3956580.0,845059.0,11250000.0,3.068412e+06
Philadelphia 76ers,2.213778e+06,1037084.5,525093.0,6500000.0,1.900402e+06
Phoenix Suns,4.229676e+06,2041080.0,55722.0,13500000.0,5.022561e+06
Portland Trail Blazers,3.220121e+06,2854940.0,525093.0,8042895.0,2.392741e+06
Sacramento Kings,4.778911e+06,3156600.0,525093.0,15851950.0,4.701792e+06
San Antonio Spurs,5.629516e+06,2814000.0,200600.0,19689000.0,6.396804e+06
Toronto Raptors,4.741174e+06,2900000.0,245177.0,13600000.0,4.195943e+06
Utah Jazz,4.204006e+06,2433333.0,900000.0,15409570.0,4.467878e+06
Washington Wizards,5.088576e+06,4000000.0,200600.0,15851950.0,4.869388e+06

In [6]:
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
grp= df2.groupby('Species')

In [8]:
grp.describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [9]:
summ = grp.agg(['mean','median', 'max'])
summ

                    Id             SepalLengthCm             SepalWidthCm  \
                  mean median  max          mean median  max         mean
Species
Iris-setosa       25.5   25.5   50         5.006    5.0  5.8        3.418
Iris-versicolor   75.5   75.5  100         5.936    5.9  7.0        2.770
Iris-virginica   125.5  125.5  150         6.588    6.5  7.9        2.974

                            PetalLengthCm             PetalWidthCm
                median  max          mean median  max         mean median  max
Species
Iris-setosa        3.4  4.4         1.464   1.50  1.9        0.244    0.2  0.6
Iris-versicolor    2.8  3.4         4.260   4.35  5.1        1.326    1.3  1.8
Iris-virginica     3.0  3.8         5.552   5.55  6.9        2.026    2.0  2.5

In [11]:
grp.quantile([0.25 , 0.75])

                          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa     0.25   13.25          4.800         3.125          1.400
                0.75   37.75          5.200         3.675          1.575
Iris-versicolor 0.25   63.25          5.600         2.525          4.000
                0.75   87.75          6.300         3.000          4.600
Iris-virginica  0.25  113.25          6.225         2.800          5.100
                0.75  137.75          6.900         3.175          5.875

                      PetalWidthCm
Species
Iris-setosa     0.25           0.2
                0.75           0.3
Iris-versicolor 0.25           1.2
                0.75           1.5
Iris-virginica  0.25           1.8
                0.75           2.3